# Generated by Django 4.1.2 on 2022-11-28 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RecentReports',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_name', models.CharField(max_length=200)),
                ('sky', models.CharField(max_length=200)),
                ('temp', models.CharField(max_length=200)),
                ('water_temp', models.CharField(max_length=200)),
                ('lures', models.CharField(max_length=200)),
                ('fish_caught', models.FloatField()),
                ('species_caught', models.CharField(max_length=200)),
                ('hours_fished', models.FloatField()),
                ('report_image', models.ImageField(upload_to='images')),
            ],
        ),
    ]
