# Generated by Django 4.1.2 on 2022-11-28 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitzfishing', '0003_topseason'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recentreports',
            name='fish_caught',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='recentreports',
            name='lures',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='topmonth',
            name='fish_caught',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='topmonth',
            name='trips',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='topseason',
            name='fish_caught',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='topseason',
            name='trips',
            field=models.CharField(max_length=200),
        ),
    ]
