# Generated by Django 4.1.2 on 2022-11-28 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitzfishing', '0004_alter_recentreports_fish_caught_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topmonth',
            name='average',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='topseason',
            name='average',
            field=models.CharField(max_length=200),
        ),
    ]
