# Generated by Django 4.1.2 on 2022-11-29 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitzfishing', '0005_alter_topmonth_average_alter_topseason_average'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recentreports',
            name='report_image',
            field=models.CharField(max_length=500),
        ),
    ]
