# Generated by Django 4.1.2 on 2022-12-01 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitzfishing', '0006_alter_recentreports_report_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='FishCaught2018',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_name', models.CharField(max_length=200)),
                ('total', models.CharField(max_length=200)),
                ('percent', models.CharField(max_length=200)),
            ],
        ),
        migrations.AlterField(
            model_name='recentreports',
            name='report_image',
            field=models.CharField(default='', max_length=500),
        ),
    ]
