# Generated by Django 4.1.2 on 2022-12-01 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitzfishing', '0007_fishcaught2018_alter_recentreports_report_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='FishCaughtMonth2018',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month_name', models.CharField(max_length=200)),
                ('total', models.CharField(max_length=200)),
                ('percent', models.CharField(max_length=200)),
            ],
        ),
    ]
