# Generated by Django 4.1.2 on 2022-12-02 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitzfishing', '0010_fishcaughtseason2018'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ratings2018',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.CharField(max_length=200)),
                ('range', models.CharField(max_length=200)),
            ],
        ),
    ]
