# Generated by Django 4.1.2 on 2022-12-02 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitzfishing', '0011_ratings2018'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportData2018',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_name', models.CharField(max_length=200)),
                ('fish_caught', models.CharField(max_length=200)),
                ('species_caught', models.CharField(max_length=200)),
            ],
        ),
    ]
