# Generated by Django 4.1.2 on 2022-12-02 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitzfishing', '0012_reportdata2018'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportdata2018',
            name='date',
            field=models.CharField(default='date', max_length=200),
        ),
    ]
