# Generated by Django 4.1.2 on 2022-12-02 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitzfishing', '0013_reportdata2018_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reportdata2018',
            name='date',
        ),
        migrations.AddField(
            model_name='reportdata2018',
            name='date1',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='reportdata2018',
            name='date10',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='reportdata2018',
            name='date11',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='reportdata2018',
            name='date12',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='reportdata2018',
            name='date2',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='reportdata2018',
            name='date3',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='reportdata2018',
            name='date4',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='reportdata2018',
            name='date5',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='reportdata2018',
            name='date6',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='reportdata2018',
            name='date7',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='reportdata2018',
            name='date8',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='reportdata2018',
            name='date9',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
