# Generated by Django 4.1.2 on 2022-12-02 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitzfishing', '0015_alter_reportdata2018_date1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportdata2018',
            name='date1',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='reportdata2018',
            name='date10',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='reportdata2018',
            name='date11',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='reportdata2018',
            name='date12',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='reportdata2018',
            name='date2',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='reportdata2018',
            name='date3',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='reportdata2018',
            name='date4',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='reportdata2018',
            name='date5',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='reportdata2018',
            name='date6',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='reportdata2018',
            name='date7',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='reportdata2018',
            name='date8',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='reportdata2018',
            name='date9',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
