# Generated by Django 4.1.2 on 2022-12-12 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitzfishing', '0019_overallstats_location_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='OverallPaginator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_name', models.CharField(max_length=200)),
            ],
        ),
        migrations.DeleteModel(
            name='OverallStats',
        ),
    ]
